name: php

toolstack: "php:drupal"

relationships:
    database: "mysql:mysql"
    redis: "redis:redis"

web:
    document_root: "/"
    passthru: "/index.php"

disk: 2048

mounts:
    "/public/sites/default/files": "shared:files/files"
    "/tmp": "shared:files/tmp"
    "/private": "shared:files/private"

runtime:
    extensions:
        - redis

hooks:
    build: |
        set -e
        cd public/sites/all/modules/contrib/election_livestats/node
        npm install
    deploy: "cd public ; drush -y updatedb"

crons:
    drupal:
        spec: "*/20 * * * *"
        cmd: "cd public ; drush core-cron"
